baseurl = "https://lcc-sosci.netlify.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Lower Columbia Social Sciences"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "An unofficial website of the Social Science Department at Lower Columbia College"
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  #name = "Some Person"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "lcc-sosci"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1
    
[[menu.main]]
    identifier = "faculty"
    name = "Faculty"
    weight = 1
    
[[menu.main]]
    parent = "faculty"
    name = "Trey Batey"
    url = "page/faculty/trey"
    weight = 2
    
[[menu.main]]
    parent = "faculty"
    name = "Jim Franz"
    url = "page/faculty/jim"
    weight = 3

[[menu.main]]
    parent = "faculty"
    name = "Mary Leach"
    url = "page/faculty/mary"
    weight = 4
    
[[menu.main]]
    parent = "faculty"
    name = "Joanna Mosser"
    url = "page/faculty/joanna"
    weight = 5
    
[[menu.main]]
    parent = "faculty"
    name = "Anita Quirk"
    url = "page/faculty/anita"
    weight = 6

[[menu.main]]
    parent = "faculty"
    name = "Courney Shah"
    url = "page/faculty/courtney"
    weight = 7

[[menu.main]]
    parent = "faculty"
    name = "Michael Strayer"
    url = "page/faculty/michael"
    weight = 8
    
[[menu.main]]
    parent = "faculty"
    name = "Nonnie Weaver"
    url = "page/faculty/nonnie"
    weight = 9

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 1
